In [46]:
import numpy as np

In [6]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [16]:
np.linspace(0, 30 ,11)
np.linspace(0, 5, 5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [158]:
arr_3d = np.arange(70)
arr_3d.shape = (2, 7, 5)
arr_3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [173]:
arr_3d * 5 - 10
arr_3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [163]:
left_mat = np.arange(6).reshape((2, 3))
right_mat = np.arange(15).reshape((3, 5))

In [164]:
dot_product = np.dot(left_mat, right_mat)

In [165]:
print(left_mat)
print(right_mat)
dot_product

[[0 1 2]
 [3 4 5]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118]])

In [166]:
arr_3d.shape

(2, 7, 5)

In [167]:
arr_3d.sum()

2415

In [176]:
arr_3d.sum(axis=2)

array([[ 10,  35,  60,  85, 110, 135, 160],
       [185, 210, 235, 260, 285, 310, 335]])

In [174]:
arr_3d.sum(axis=0)

array([[ 35,  37,  39,  41,  43],
       [ 45,  47,  49,  51,  53],
       [ 55,  57,  59,  61,  63],
       [ 65,  67,  69,  71,  73],
       [ 75,  77,  79,  81,  83],
       [ 85,  87,  89,  91,  93],
       [ 95,  97,  99, 101, 103]])

In [177]:
arr_2d = np.arange(25).reshape((5, 5))
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [184]:
arr_2d.sum(axis=0)

array([50, 55, 60, 65, 70])

### broadcastin

In [186]:
arr_2d = np.ones(35, dtype=int).reshape((7, 5)) * 5
arr_2d

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [187]:
rand_2d = np.random.random((7, 5))
rand_2d

array([[0.6414032 , 0.47391686, 0.66950594, 0.61873581, 0.91450255],
       [0.94294728, 0.96892195, 0.90170162, 0.61096877, 0.19136427],
       [0.85225598, 0.50671101, 0.73914515, 0.63600554, 0.42590684],
       [0.79550349, 0.05408543, 0.40024855, 0.82101059, 0.05409225],
       [0.10237997, 0.56766494, 0.66698416, 0.6572977 , 0.01579345],
       [0.55285397, 0.30061142, 0.56804588, 0.39519771, 0.89524915],
       [0.14599165, 0.73526879, 0.93335036, 0.41377804, 0.75445082]])

In [191]:
np.set_printoptions(precision=4)
arr_3d * rand_2d

array([[[ 0.    ,  0.4739,  1.339 ,  1.8562,  3.658 ],
        [ 4.7147,  5.8135,  6.3119,  4.8878,  1.7223],
        [ 8.5226,  5.5738,  8.8697,  8.2681,  5.9627],
        [11.9326,  0.8654,  6.8042, 14.7782,  1.0278],
        [ 2.0476, 11.921 , 14.6737, 15.1178,  0.379 ],
        [13.8213,  7.8159, 15.3372, 11.0655, 25.9622],
        [ 4.3797, 22.7933, 29.8672, 13.6547, 25.6513]],

       [[22.4491, 17.061 , 24.7717, 23.512 , 35.6656],
        [37.7179, 39.7258, 37.8715, 26.2717,  8.42  ],
        [38.3515, 23.3087, 34.7398, 30.5283, 20.8694],
        [39.7752,  2.7584, 20.8129, 43.5136,  2.921 ],
        [ 5.6309, 31.7892, 38.0181, 38.1233,  0.9318],
        [33.1712, 18.3373, 35.2188, 24.8975, 57.2959],
        [ 9.4895, 48.5277, 62.5345, 28.1369, 52.0571]]])

In [192]:
vec = np.arange(5) * 7
vec[0] = -1
vec

array([-1,  7, 14, 21, 28])

In [193]:
arr_3d / vec

array([[[ -0.    ,   0.1429,   0.1429,   0.1429,   0.1429],
        [ -5.    ,   0.8571,   0.5   ,   0.381 ,   0.3214],
        [-10.    ,   1.5714,   0.8571,   0.619 ,   0.5   ],
        [-15.    ,   2.2857,   1.2143,   0.8571,   0.6786],
        [-20.    ,   3.    ,   1.5714,   1.0952,   0.8571],
        [-25.    ,   3.7143,   1.9286,   1.3333,   1.0357],
        [-30.    ,   4.4286,   2.2857,   1.5714,   1.2143]],

       [[-35.    ,   5.1429,   2.6429,   1.8095,   1.3929],
        [-40.    ,   5.8571,   3.    ,   2.0476,   1.5714],
        [-45.    ,   6.5714,   3.3571,   2.2857,   1.75  ],
        [-50.    ,   7.2857,   3.7143,   2.5238,   1.9286],
        [-55.    ,   8.    ,   4.0714,   2.7619,   2.1071],
        [-60.    ,   8.7143,   4.4286,   3.    ,   2.2857],
        [-65.    ,   9.4286,   4.7857,   3.2381,   2.4643]]])

 ## structed arrays

In [205]:
employee_data_def = [('name', 'S6'), ('height', 'f8'), ('weight', 'f8'),
                     ('age', 'i8')]
employee_data_def

[('name', 'S6'), ('height', 'f8'), ('weight', 'f8'), ('age', 'i8')]

In [206]:
employees_array = np.zeros((4), dtype=employee_data_def)
employees_array

array([(b'', 0., 0., 0), (b'', 0., 0., 0), (b'', 0., 0., 0),
       (b'', 0., 0., 0)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [207]:
employees_array[3] = ("donatello", 200, 100, 105)

In [208]:
employees_array[0] = ('rafael', 198, 99, 89)

In [209]:
employees_array

array([(b'rafael', 198.,  99.,  89), (b'',   0.,   0.,   0),
       (b'',   0.,   0.,   0), (b'donate', 200., 100., 105)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [212]:
employees_array[2:]

array([(b'',   0.,   0.,   0), (b'donate', 200., 100., 105)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [214]:
ages = employees_array['age']
ages

array([ 89,   0,   0, 105])

In [221]:
company_employees_all = np.zeros((4, 3, 2), dtype=employee_data_def)
company_employees_all

array([[[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]],

       [[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]],

       [[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]],

       [[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]]],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [222]:
company_employees_all[3, 2, 1] = ('pipin', 90, 120, 98)
company_employees_all

array([[[(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
        [(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
        [(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)]],

       [[(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
        [(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
        [(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)]],

       [[(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
        [(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
        [(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)]],

       [[(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
        [(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
        [(b'',  0.,   0.,  0), (b'pipin', 90., 120., 98)]]],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [226]:
company_employees_all[['height', 'weight']]

array([[[( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)]],

       [[( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)]],

       [[( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)]],

       [[( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), (90., 120.)]]],
      dtype={'names':['height','weight'], 'formats':['<f8','<f8'], 'offsets':[6,14], 'itemsize':30})

In [227]:
ave_array = np.arange(24).reshape((2, 3, 4))
ave_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [296]:
trial_ave_array = np.append(ave_array, [5, 6, 7, 8])
trial_ave_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23,  5,  6,  7,  8])

In [231]:
trial_ave_array.reshape(7, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 5,  6,  7,  8]])

In [233]:
new_trial_array = np.arange(24).reshape(2, 3, 4) * 10 + 5
new_trial_array

array([[[  5,  15,  25,  35],
        [ 45,  55,  65,  75],
        [ 85,  95, 105, 115]],

       [[125, 135, 145, 155],
        [165, 175, 185, 195],
        [205, 215, 225, 235]]])

In [250]:
np.append(ave_array, new_trial_array, axis=2)

array([[[  0,   1,   2,   3,   5,  15,  25,  35],
        [  4,   5,   6,   7,  45,  55,  65,  75],
        [  8,   9,  10,  11,  85,  95, 105, 115]],

       [[ 12,  13,  14,  15, 125, 135, 145, 155],
        [ 16,  17,  18,  19, 165, 175, 185, 195],
        [ 20,  21,  22,  23, 205, 215, 225, 235]]])

In [247]:
np.append(ave_array, new_trial_array, axis=1).shape

(2, 6, 4)

In [252]:
ave_stack = np.hstack((ave_array, new_trial_array))
ave_stack

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  5,  15,  25,  35],
        [ 45,  55,  65,  75],
        [ 85,  95, 105, 115]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [125, 135, 145, 155],
        [165, 175, 185, 195],
        [205, 215, 225, 235]]])

## how insert works

In [253]:
ave_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [259]:
ave_array.shape

(2, 3, 4)

In [254]:
insert_ave_array = np.insert(ave_array, 1, 666, axis=0)
insert_ave_array

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[666, 666, 666, 666],
        [666, 666, 666, 666],
        [666, 666, 666, 666]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])

In [260]:
insert_ave_array = np.insert(ave_array, 1, 666, axis=2)
insert_ave_array

array([[[  0, 666,   1,   2,   3],
        [  4, 666,   5,   6,   7],
        [  8, 666,   9,  10,  11]],

       [[ 12, 666,  13,  14,  15],
        [ 16, 666,  17,  18,  19],
        [ 20, 666,  21,  22,  23]]])

In [264]:
del_array = np.empty(ave_array.shape)
np.copyto(del_array, ave_array)
print(del_array.shape)
del_array

(2, 3, 4)


array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]],

       [[12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]]])

In [268]:
np.delete(del_array, 1, axis=2)

array([[[ 0.,  2.,  3.],
        [ 4.,  6.,  7.],
        [ 8., 10., 11.]],

       [[12., 14., 15.],
        [16., 18., 19.],
        [20., 22., 23.]]])

In [280]:
alpha = np.array([[1,2],[3,4]])
beta= np.array([[5,6]])
alpha

array([[1, 2],
       [3, 4]])

In [289]:
beta.shape


(1, 2)

In [316]:
np.insert(alpha,0,  beta, axis=1)

array([[5, 1, 2],
       [6, 3, 4]])

In [312]:
together = np.concatenate((alpha, beta), axis=0)
print(together.shape)
together


(3, 2)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [297]:
together[1, 1] = 666
together

array([[  1,   2],
       [  3, 666],
       [  5,   6]])

In [319]:
arrays = np.zeros((5,3,4))
for n in range(5):
    arrays[n] = np.random.randn(3,4)
arrays

array([[[-2.2725,  0.4001, -0.0239,  0.0993],
        [ 0.3305,  0.2358, -0.2278,  0.9284],
        [ 2.2493, -0.4867,  0.762 , -0.8607]],

       [[-1.199 ,  0.9853,  0.4138,  1.5336],
        [-0.8912, -0.1758,  0.7392,  2.0034],
        [ 0.2767,  0.4127,  0.2689, -1.3025]],

       [[ 0.1731, -2.745 , -0.5701, -0.2247],
        [-0.2688, -1.6549, -1.4476,  0.7977],
        [ 0.839 , -0.1126,  0.4714,  0.6549]],

       [[ 0.3342,  2.337 , -0.3095, -0.4274],
        [-1.5615,  1.0063, -0.0182,  0.379 ],
        [ 1.1953, -0.1594, -0.3891, -1.0061]],

       [[ 0.6619, -1.6168, -0.2407,  1.7098],
        [-0.0078, -1.2291,  1.6535, -0.9557],
        [-0.6724, -1.3686, -0.7598,  0.4938]]])

In [320]:
stack0= np.stack(arrays, axis=0)
stack1= np.stack(arrays, axis=1)
stack2= np.stack(arrays, axis=2)

In [321]:
stack0

array([[[-2.2725,  0.4001, -0.0239,  0.0993],
        [ 0.3305,  0.2358, -0.2278,  0.9284],
        [ 2.2493, -0.4867,  0.762 , -0.8607]],

       [[-1.199 ,  0.9853,  0.4138,  1.5336],
        [-0.8912, -0.1758,  0.7392,  2.0034],
        [ 0.2767,  0.4127,  0.2689, -1.3025]],

       [[ 0.1731, -2.745 , -0.5701, -0.2247],
        [-0.2688, -1.6549, -1.4476,  0.7977],
        [ 0.839 , -0.1126,  0.4714,  0.6549]],

       [[ 0.3342,  2.337 , -0.3095, -0.4274],
        [-1.5615,  1.0063, -0.0182,  0.379 ],
        [ 1.1953, -0.1594, -0.3891, -1.0061]],

       [[ 0.6619, -1.6168, -0.2407,  1.7098],
        [-0.0078, -1.2291,  1.6535, -0.9557],
        [-0.6724, -1.3686, -0.7598,  0.4938]]])

In [322]:
stack1

array([[[-2.2725,  0.4001, -0.0239,  0.0993],
        [-1.199 ,  0.9853,  0.4138,  1.5336],
        [ 0.1731, -2.745 , -0.5701, -0.2247],
        [ 0.3342,  2.337 , -0.3095, -0.4274],
        [ 0.6619, -1.6168, -0.2407,  1.7098]],

       [[ 0.3305,  0.2358, -0.2278,  0.9284],
        [-0.8912, -0.1758,  0.7392,  2.0034],
        [-0.2688, -1.6549, -1.4476,  0.7977],
        [-1.5615,  1.0063, -0.0182,  0.379 ],
        [-0.0078, -1.2291,  1.6535, -0.9557]],

       [[ 2.2493, -0.4867,  0.762 , -0.8607],
        [ 0.2767,  0.4127,  0.2689, -1.3025],
        [ 0.839 , -0.1126,  0.4714,  0.6549],
        [ 1.1953, -0.1594, -0.3891, -1.0061],
        [-0.6724, -1.3686, -0.7598,  0.4938]]])

In [323]:
stack2

array([[[-2.2725, -1.199 ,  0.1731,  0.3342,  0.6619],
        [ 0.4001,  0.9853, -2.745 ,  2.337 , -1.6168],
        [-0.0239,  0.4138, -0.5701, -0.3095, -0.2407],
        [ 0.0993,  1.5336, -0.2247, -0.4274,  1.7098]],

       [[ 0.3305, -0.8912, -0.2688, -1.5615, -0.0078],
        [ 0.2358, -0.1758, -1.6549,  1.0063, -1.2291],
        [-0.2278,  0.7392, -1.4476, -0.0182,  1.6535],
        [ 0.9284,  2.0034,  0.7977,  0.379 , -0.9557]],

       [[ 2.2493,  0.2767,  0.839 ,  1.1953, -0.6724],
        [-0.4867,  0.4127, -0.1126, -0.1594, -1.3686],
        [ 0.762 ,  0.2689,  0.4714, -0.3891, -0.7598],
        [-0.8607, -1.3025,  0.6549, -1.0061,  0.4938]]])

In [324]:
before_split = stack0
before_split.shape

(5, 3, 4)

In [326]:
s0 = np.split(before_split, 5, axis=0)
s0

5

In [330]:
s1= np.split(before_split, 3, axis=1)
s1

[array([[[-2.2725,  0.4001, -0.0239,  0.0993]],
 
        [[-1.199 ,  0.9853,  0.4138,  1.5336]],
 
        [[ 0.1731, -2.745 , -0.5701, -0.2247]],
 
        [[ 0.3342,  2.337 , -0.3095, -0.4274]],
 
        [[ 0.6619, -1.6168, -0.2407,  1.7098]]]),
 array([[[ 0.3305,  0.2358, -0.2278,  0.9284]],
 
        [[-0.8912, -0.1758,  0.7392,  2.0034]],
 
        [[-0.2688, -1.6549, -1.4476,  0.7977]],
 
        [[-1.5615,  1.0063, -0.0182,  0.379 ]],
 
        [[-0.0078, -1.2291,  1.6535, -0.9557]]]),
 array([[[ 2.2493, -0.4867,  0.762 , -0.8607]],
 
        [[ 0.2767,  0.4127,  0.2689, -1.3025]],
 
        [[ 0.839 , -0.1126,  0.4714,  0.6549]],
 
        [[ 1.1953, -0.1594, -0.3891, -1.0061]],
 
        [[-0.6724, -1.3686, -0.7598,  0.4938]]])]

In [331]:
ave_start = np.arange(24)
ave_start

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [332]:
ave_3_8_rate = ave_start.reshape((3,8))
ave_3_8_rate

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [333]:
ave_ravel_array = ave_3_8_rate.ravel()
ave_ravel_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [336]:
flat = ave_3_8_rate.flatten()
flat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [337]:
for n in ave_3_8_rate.flat:
    print(n)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [338]:
ave_start_array = np.arange(24)
ave_3_8_array = ave_start_array.reshape((3,8))
ave_2_3_4_array = ave_3_8_array.reshape((2,3,4))

In [339]:
ave_3_8_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [340]:
np.fliplr(ave_3_8_array)

array([[ 7,  6,  5,  4,  3,  2,  1,  0],
       [15, 14, 13, 12, 11, 10,  9,  8],
       [23, 22, 21, 20, 19, 18, 17, 16]])

In [341]:
ave_2_3_4_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [342]:
np.fliplr(ave_2_3_4_array)

array([[[ 8,  9, 10, 11],
        [ 4,  5,  6,  7],
        [ 0,  1,  2,  3]],

       [[20, 21, 22, 23],
        [16, 17, 18, 19],
        [12, 13, 14, 15]]])

In [343]:
ave_3_8_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [345]:
np.flipud(ave_3_8_array)

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [ 0,  1,  2,  3,  4,  5,  6,  7]])

In [346]:
np.flipud(ave_2_3_4_array)

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [347]:
ave_start_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [348]:
np.roll(ave_start_array, 5)

array([19, 20, 21, 22, 23,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
       12, 13, 14, 15, 16, 17, 18])

In [349]:
np.roll(ave_start_array, -5)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23,  0,  1,  2,  3,  4])

In [351]:
ave_2_3_4_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [352]:
np.roll(ave_2_3_4_array, 2)

array([[[22, 23,  0,  1],
        [ 2,  3,  4,  5],
        [ 6,  7,  8,  9]],

       [[10, 11, 12, 13],
        [14, 15, 16, 17],
        [18, 19, 20, 21]]])

In [353]:
ave_3_8_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [354]:
np.roll(ave_3_8_array, 3)

array([[21, 22, 23,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20]])

In [355]:
ave_3_8_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [358]:
np.rot90(ave_3_8_array)

array([[ 7, 15, 23],
       [ 6, 14, 22],
       [ 5, 13, 21],
       [ 4, 12, 20],
       [ 3, 11, 19],
       [ 2, 10, 18],
       [ 1,  9, 17],
       [ 0,  8, 16]])

In [360]:
ave_array_one = np.arange(10)
ave_array_one

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [364]:
np.tile(ave_array_one,5).reshape(5,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [365]:
ave_array_two = np.array(np.arange(7))
tile1 = np.tile(ave_array_two,(3,1))
tile1

array([[0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6]])

In [366]:
np.repeat(ave_array_two, 3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6])

In [370]:
np.full(2, 3)

array([3, 3])

In [372]:
np.zeros(2)

array([0., 0.])

In [373]:
np.ones(4)

array([1., 1., 1., 1.])

In [388]:
zeros = (np.zeros(2) + 1) * 5
zeros.dtype

dtype('float64')

In [386]:
np.full((2,),2)

array([2, 2])